import{a as b,S as v,i as a}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const P="44654368-4937825c1744fe72f2410636e",I="https://pixabay.com/api/";async function p(e,r=1,o=15){try{const s=await b.get(`${I}`,{params:{key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:o}});if(console.log("API response:",s.data),s.status!==200)throw new Error("Error fetching data from API");return s.data}catch(s){throw console.error("API request error:",s),s}}const y=document.querySelector(".gallery");function S(){y.innerHTML=""}const q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function E(e){const r=e.map(o=>A(o)).join("");y.insertAdjacentHTML("beforeend",r),q.refresh()}function A({webformatURL:e,largeImageURL:r,tags:o,likes:s,views:t,comments:n,downloads:c}){return`
    <div class="photo-card">
      <a href="${r}" class="gallery-link">
        <img src="${e}" alt="${o}" loading="lazy" class="gallery-image"/>
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${s}</p>
        <p class="info-item"><b>Views:</b> ${t}</p>
        <p class="info-item"><b>Comments:</b> ${n}</p>
        <p class="info-item"><b>Downloads:</b> ${c}</p>
      </div>
    </div>
  `}const $=document.querySelector(".search-form"),M=document.querySelector(".search-input"),h=document.querySelector(".load-more"),d=document.querySelector(".loader"),f=15;let i=1,L="",l=0,u=0;$.addEventListener("submit",C);h.addEventListener("click",x);async function C(e){e.preventDefault();const r=M.value.trim();if(!r){a.error({title:"Error",message:"Please enter a search query."});return}L=r,i=1,l=0,u=0,S(),g(),w();try{const o=await p(r,i,f);if(!o||!o.hits)throw console.error("Invalid response structure:",o),new Error("Invalid response from API");const s=o.hits;if(l=o.totalHits,u=Math.ceil(l/f),m(),s.length===0){a.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"});return}E(s),a.success({title:"Success",message:`Found ${l} images.`}),i<u&&N()}catch(o){m(),a.error({title:"Error",message:`An error occurred while searching for images. Please try again later. Error: ${o.message}`}),console.error("Error during search:",o)}}async function x(){i+=1,w();try{const e=await p(L,i,f);if(!e||!e.hits)throw console.error("Invalid response structure:",e),new Error("Invalid response from API");const r=e.hits;if(m(),r.length===0){a.info({title:"End of List",message:"No more images for this search query."}),g();return}E(r),B(),i>=u&&(g(),a.info({title:"No More Images",message:"You have reached the end of the search results."}))}catch(e){m(),a.error({title:"Error",message:`An error occurred while loading more images. Please try again later. Error: ${e.message}`}),console.error("Error during loading more images:",e)}}function B(){const e=document.querySelector(".gallery");if(e){const{height:r}=e.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}else console.error("Element with class .gallery not found.")}function w(){d.textContent="Loading images, please wait...",d.classList.remove("hidden")}function m(){d.classList.add("hidden"),d.textContent=""}function N(){h.classList.remove("hidden")}function g(){h.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
